name: Update groups.csv
on:
  workflow_dispatch:
    inputs:
      ad_group_name:
        description: "AD group Name"     
        required: true
jobs:
  updateOctokitStats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # fetch statistics for @octokit org
      - uses: gr2m/org-stats-action@v1.x
        id: stats
        with:
          org: octokit
        env:
          GITHUB_TOKEN: ${{ secrets.NEW_GITHUB_TOKEN }}
      # append stats to testusers.csv
      - uses: gr2m/write-csv-file-action@v1.x
        with:
          path: groups.csv
          columns: group_name
          "group_name": ${{ inputs.ad_group_name }}
      # push updated file back to main branch
      - run: git config --local user.email "action@github.com"
      - run: git config --local user.name "GitHub Action"
      - run: git add groups.csv
      - run: git commit -m "groups.csv updated"
      - run: "git push https://x-access-token:${NEW_GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git main"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
