name: Update users.csv
on:
  workflow_dispatch:
    inputs:
      user_firstname:
        description: "User First Name"     
        required: true
      user_lastname:
        description: "User Last Name"     
        required: true
      user_action:
        type: choice
        description: "Please select a user action"
        required: true
        options:
          - "Create User"
          - "Update User"
      department:
        type: choice
        description: "User Department"
        required: true
        options: 
        - DevOps
        - QA
      job_title:
        type: choice
        description: "User Job title"
        required: true
        options: 
        - Engineer
        - Manager
      group1:
        type: boolean
        required: true
        description: group1
      group2:
        type: boolean
        required: true
        description: group2
      group3:
        type: boolean
        required: true
        description: group3
      
jobs:
  createnewusers:
    if: inputs.user_action === 'Create User'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # fetch statistics for @octokit org
      - uses: gr2m/org-stats-action@v1.x
        id: stats
        with:
          org: octokit
        env:
          GITHUB_TOKEN: ${{ secrets.NEW_GITHUB_TOKEN }}
      # append stats to testusers.csv
      - uses: gr2m/write-csv-file-action@v1.x
        with:
          path: users.csv
          columns: first_name,last_name,department,job_title,user_principal_name,group1,group2,group3
          "first_name": ${{ inputs.user_firstname }}
          "last_name": ${{ inputs.user_lastname }}
          "department": ${{ inputs.department }}
          "job_title": ${{ inputs.job_title }}
          "user_principal_name": ${{ inputs.user_firstname }}.${{ inputs.user_lastname }}@SalesledzPvtLtd.onmicrosoft.com
          "group1": ${{ inputs.group1 }}
          "group2": ${{ inputs.group2 }}
          "group3": ${{ inputs.group3 }}
      # push updated file back to main branch
      - run: git config --local user.email "action@github.com"
      - run: git config --local user.name "GitHub Action"
      - run: git add users.csv
      - run: git commit -m "users.csv updated"
      - run: "git push https://x-access-token:${NEW_GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git main"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  updateusers:
    if: inputs.user_action === 'Update User'
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.7' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run updateuser.py to get the latest data
        env: 
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        run: python updateuser.py
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "update data" -a
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
